Write a python Program for Bidirectional Associative Memory with two pairs of vectors.

In [12]:
import numpy as np

In [13]:
# Input Patterns
x1 = np.array([1,-1,1,-1,1,-1]).reshape(6,1)
x2 = np.array([1,-1,1,1,-1,1]).reshape(6,1)
x3 = np.array([-1,-1,-1,-1,-1,-1]).reshape(6,1)
x4 = np.array([1,1,-1,1,1,-1]).reshape(6,1)

# Output Patterns
y1 = np.array([1,-1,1]).reshape(3,1)
y2 = np.array([1,-1,1]).reshape(3,1)
y3 = np.array([-1,-1,-1]).reshape(3,1)
y4 = np.array([1,1,-1]).reshape(3,1)


In [14]:
# Calculating weights
w1 = y1@x1.T
w2 = y2@x2.T
w3 = y3@x3.T
w4 = y4@x4.T

print("Weight1: \n",w1)
print("Weight2: \n",w2)
print("Weight3: \n",w3)
print("Weight4: \n",w4)

Weight1: 
 [[ 1 -1  1 -1  1 -1]
 [-1  1 -1  1 -1  1]
 [ 1 -1  1 -1  1 -1]]
Weight2: 
 [[ 1 -1  1  1 -1  1]
 [-1  1 -1 -1  1 -1]
 [ 1 -1  1  1 -1  1]]
Weight3: 
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Weight4: 
 [[ 1  1 -1  1  1 -1]
 [ 1  1 -1  1  1 -1]
 [-1 -1  1 -1 -1  1]]


In [15]:
def sigmoid(weight):
    temp = []
    for i in weight:
        if i > 0:
            temp.append(1)
        else:
            temp.append(-1)
    return temp

In [16]:
# Output Predicted
Ym1 = sigmoid(w1@x1)
print(Ym1)
Ym2 = sigmoid(w2@x2)
print(Ym2)
Ym3 = sigmoid(w3@x3)
print(Ym3)
Ym4 = sigmoid(w4@x4)
print(Ym4)

[1, -1, 1]
[1, -1, 1]
[-1, -1, -1]
[1, 1, -1]


In [17]:
# Input from Predicted Output
Xm1 = sigmoid(Ym1@w1)
print(Xm1)
Xm2 = sigmoid(Ym2@w2)
print(Xm2)
Xm3 = sigmoid(Ym3@w3)
print(Xm3)
Xm4 = sigmoid(Ym4@w4)
print(Xm4)

[1, -1, 1, -1, 1, -1]
[1, -1, 1, 1, -1, 1]
[-1, -1, -1, -1, -1, -1]
[1, 1, -1, 1, 1, -1]
